services:
  postgres:
    image: postgres:17-alpine
    container_name: hinge-postgres
    environment:
      POSTGRES_DB: hinge_db
      POSTGRES_USER: hinge_service
      POSTGRES_PASSWORD: hinge_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_hinge_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hinge_service -d hinge_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_hinge_data: